const data = {
  products: [
    {
      name: "Cute necklace",
      slug: "cute-necklace",
      category: "Necklaces",
      image: "/images/stockvault-diamond-necklace98449.jpg",
      price: "$15",
      brand: "urban unique",
      rating: 4.7,
      numReviews: 10,
      countInStock: 6,
      description: "a popular necklace that is cute and fashionable",
    },
    {
      name: "Cute bracelet",
      slug: "cute-bracelet",
      category: "Bracelets",
      image: "/images/stockvault-bracelet110241.jpg",
      price: "$10",
      brand: "urban unique",
      rating: 4.8,
      numReviews: 10,
      countInStock: 17,
      description: "a cute bracelet that grabs attention",
    },
    {
      name: "Pretty bow",
      slug: "pretty-bow",
      category: "Bows",
      image: "/images/stockvault-ribbon161049.jpg",
      price: "$3",
      brand: "urban unique",
      rating: 5,
      numReviews: 7,
      countInStock: 38,
      description: "a bow that for those who like to accessorize",
    },
    {
      name: "Heart earrings",
      slug: "heart-earrings",
      category: "earrings",
      image: "/images/stockvault-ring-and-heart98470.jpg",
      price: "$8",
      brand: "urban unique",
      rating: 4.4,
      numReviews: 20,
      countInStock: 12,
      description: "a lovely fun set of earrings",
    },
    {
      name: "Pink hair beads",
      slug: "pink-hair-beads",
      category: "Hair-styling",
      image: "/images/stockvault-beaded-lamp108503.jpg",
      price: "$10",
      brand: "urban unique",
      rating: 4.9,
      numReviews: 25,
      countInStock: 17,
      description: "a colorful set of beads for styling ethnic hair",
    },
    {
      name: "Vibrant press on nails",
      slug: "vibrant-press-on-nails",
      category: "Nails",
      image: "/images/stockvaulr-une-belle-french-manucure185.100.jpg",
      price: "$20",
      brand: "urban unique",
      rating: 5,
      numReviews: 25,
      countInStock: 4,
      description: "an eyecatching set of press on nails",
    },
  ],
};

export default data
